max_width = 135
chain_width = 90
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
struct_lit_single_line = true
fn_single_line = true
where_single_line = true
empty_item_single_line = true
reorder_imports = true
reorder_impl_items = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
struct_field_align_threshold = 40
enum_discrim_align_threshold = 40
wrap_comments = true
format_strings = true
doc_comment_code_block_width = 100
comment_width = 100
